### ISSUE TITLE
Create Github org to host this app

### ISSUE THREAD

**Issue by moorepants** [ucd-ipo/aip-analysis#11]
I'd like to move this application to a Github organization so it isn't under Kyle or my username. @msimmond, what would be a good org name? Is this under your lab? Or is it under a project?

**Comment by moorepants** [comment]
@lmpincus Can you suggest a short simple organization name to house this project under?

**Comment by moorepants** [comment]
BTW, AIP is taken as a top level name on Github: https://github.com/aip

**Comment by lmpincus** [comment]
The app isn't under Maegen or my lab. It is funded by USAID via the UC Davis International Programs Office. But it will go out into the world as an independent app with only minimal USAID branding. At some point we discussed putting a separate page in as a citation page that you click on to see the funding/developer info. I suggest for now we call the app "Agricultural Field Trial Statistics Package." I don't care what the GitHub name is, so feel free to pick whatever works for you.

**Comment by lmpincus** [comment]
Also, AIP is the larger USAID project we are working under. Stands for Agricultural Innovation Project. Other work under this project includes graduate student scholarships, fruit tree research, vocational training, and ICT for agricultural extension in Pakistan.

**Comment by moorepants** [comment]
Ok, that helps. But I still need a unique name for the Github organization. I want to create a Github org, i.e. `http://www.github.com/<our-org-name>`, so that I can just pass off the reins to the project to anyone that takes over in the future. The app will then be found under `http://github.com/<our-org-name>/aip-analysis` instead of `http://github.com/ikkyle/api-analysis` or `http://github.com/moorepants/aip-analysis`. Any suggestions?

Maybe UCD-AIP?

**Comment by moorepants** [comment]
Or UCD-International-Programs-Office?

**Comment by moorepants** [comment]
I'll also update the app name to what you suggest.

**Comment by lmpincus** [comment]
UCD-International-Programs-Office works.

**Comment by moorepants** [comment]
I think I'll make it UCD-IPO so it is shorter.

**Comment by moorepants** [comment]
@ikkyle Can you transfer ownership of this repo to the ucd-ipo github organization?

https://github.com/ucd-ipo
