### ISSUE TITLE
Post hoc Analysis

### ISSUE THREAD

**Issue by moorepants** [ucd-ipo/aip-analysis#14]
Add functions for multiple mean comparisons that separate treatment means using 3 methods and order them with corresponding letters using Fisher’s protected and unprotected least significant difference (LSD) and Tukey procedures. Add an option to choose significance level.
*Add a reminder that pops up that reminds them that mean separations should only be done if the that factor (treatment) is significant in the ANOVA table (i.e. p-value < their chosen sig level), unless they are doing Fisher’s Unprotected LSD.

**Comment by msimmond** [comment]
Hi Jason, we recently discussed only using 1 method, i.e. Protected Least Significant Difference, where the mean separation is only performed if the treatment effect is significant (p<0.05) in the ANOVA. When do you think this will be up and running? This function, along with testing assumptions, are really the next updates needed.

**Comment by moorepants** [comment]
I told Lauren that I will be working on all this after I'm done with a conference this week.

**Comment by msimmond** [comment]
Cool, thanks.

**Comment by moorepants** [comment]
Yeah, sorry. The hiring date for this and a ton of other stuff aligned differently that previously expected. I'll be working pretty much full time on the next couple of weeks to get things in shape.

**Comment by moorepants** [comment]
Do you have a typical function you use for PLSD?

I think this:

http://www.inside-r.org/packages/cran/agricolae/docs/LSD.test

does LSD by default but I'm not sure about "Protected".

**Comment by moorepants** [comment]
I'm thinking that LSD and PLSD is the same thing...?

**Comment by msimmond** [comment]
'Protected' means that LSD is only done if the null hypothesis in the ANOVA for that particular variable is false (i.e., p <0.05 which is significant). There is a possibility that there will be significant differences in the LSD without a significant ANOVA. Thus, there is a distinction between protected and unprotected. I'm not aware of any R functions that would strictly perform a protected LSD. I think there would need to be a conditional statement, such as: 'if(p-value for 'treatment' == <0.05, LSD(model, 'treatment', ...) Else("Mean separation cannot be performed using protected LSD because model was not significant")

**Comment by moorepants** [comment]
Ok, got it. I'll make sure that the p value is checked from the ANOVA results and just run LSD on the significant ones. I had a hard time finding what "protected" meant in this case. I thought that you were always only supposed to run these on the significant variables.

**Comment by moorepants** [comment]
@msimmond @lmpincus Where do you all ask questions about the agricolae package? Do you email the maintainer directly or is there a mailing list (can't find one)?

**Comment by moorepants** [comment]
How am I supposed to handle doing LSD with models that have interactions? This note[1] says that you shouldn't do it at all if you model has interactions.

[1] https://www.researchgate.net/post/Is_it_correct_to_compute_protected_least_significant_difference_LSD_for_the_interaction_effect_in_factorial_designs

**Comment by msimmond** [comment]
I've added the LSD tests needed for both cases (when sig interaction, and when not significant) in the examples section of the split-plot RCBD

**Comment by moorepants** [comment]
All of these have been added in PR #51
