### ISSUE TITLE
Add Split Plot Methods

### ISSUE THREAD

**Issue by moorepants** [ucd-ipo/aip-analysis#15]
There should be a dropdown function under ANOVA for split plot methods. R function available in the agricolae package (split plot only at this time).

**Comment by moorepants** [comment]
@msimmond @lmpincus Can one of you either point me to an example code for doing a split plot design or write a simple one here? I assume split plot matches some kind of experiment design in DoE.

**Comment by msimmond** [comment]
Split plot design has 2 (or more) factors for which there are 2 stages of randomization. First, one factor is assigned to the "main plots". Next, the second factor is assigned to "subplots" within each main plot. We want app capability to do a split-plot design with CRD for main plots or RCBD for main plots. Importantly, there are two error terms, so if there are post-hoc questions directed to the main plot, the error term must be specified as it is not the residuals. 

The model for the split-plot with CRD main plots: 

``` r
Y ~ MainPlot + Error(MainPlot:Rep) + Subplot + MainPlot:Subplot
```

Error term for `MainPlot = MainPlot*replication` 
Error term for `Subplot = Subplot*replication + MainPlot*Subplot*replication`

The model for the split-plot with RCBD main plots:

``` r
Y ~ Block + MainPlot + MainPlot*Block + Error(MainPlot:Block) + Subplot + MainPlot*Subplot
```

Error term for `MainPlot = MainPlot*Block`
Error term for `Subplot = residuals ==> Subplot*Block + MainPlot*Subplot*Block`

See example 1 (split-plot with RCBD) and example 2 (split-plot with CRD) in R here: http://www.unh.edu/halelab/BIOL933/labs/lab9.pdf  **Note the "BE AWARE" on pp 4 regarding specifying Reps versus Block for split-plot with CRD in R.

**Comment by moorepants** [comment]
Nice diagram comparison of CRD, RCBD, and Split Plot: http://www.public.iastate.edu/~dnett/S510/14SplitPlot.pdf

**Comment by moorepants** [comment]
Split plot designs are now supported. Closing.
