### ISSUE TITLE
Introduce Mixed Effects Option for RCBD and Split Plot

### ISSUE THREAD

**Issue by moorepants** [ucd-ipo/aip-analysis#16]
The user should be able to select the location as a random effect and the mixed effect model results computed. Should include a pop-up box explaining why location is being analyzed as a random effect.

**Comment by moorepants** [comment]
- Maegan will discuss this one with Lauren/Mark and if we need it give Jason an example to work from.

May want to support making the location random effect.

**Comment by moorepants** [comment]
@msimmond I'm having trouble finding a good example to work from for this. This lecture (http://www.unh.edu/halelab/BIOL933/lectures/lect_15.pdf) only has a single line of R code, so I'm lost reading it. Do you have any better examples?

**Comment by moorepants** [comment]
I found this: http://www.r-bloggers.com/split-plot-1-how-does-a-linear-mixed-model-look-like/

**Comment by moorepants** [comment]
This is better: https://www.stat.wisc.edu/courses/st850-lindstro/handouts/splitplotlme.pdf there seems to be a location column in addition to the blocks.

**Comment by moorepants** [comment]
Suggested reading from Maegen:

On mixed effects (also see attachment)
http://www.r-bloggers.com/linear-mixed-models-in-r/
http://www.quantumforest.com/2011/10/linear-mixed-models-in-r/
http://stats.stackexchange.com/questions/37797/understanding-the-output-of-lme
http://www.unh.edu/halelab/BIOL933/lectures/lect_15.pdf
http://www.unh.edu/halelab/BIOL933/lectures/lect_15_reading.pdf
http://www.unh.edu/halelab/BIOL933/lectures/final_review.pdf (this one has the whole course, but some on mixed effects)

**Comment by rkingdc** [comment]
chosen automatically based on experimental design.
