### ISSUE TITLE
Users should be able to download a report in PDF format.

### ISSUE THREAD

**Issue by moorepants** [ucd-ipo/aip-analysis#18]
The app should be able to print a PDF report of the functions performed.

**Comment by moorepants** [comment]
Add a popup over the graph images that remind people that they can save the images by right clicking.

Remind them that they can download R and use the code and edit the code customize further.

**Comment by moorepants** [comment]
Make option to generate an R file from the code.

**Comment by moorepants** [comment]
A basic html report is now working on the app. Making a pdf output may be more difficult than imagined. Looks like a pdf output is going to require pandoc which will require binaries for each OS on the flash drive, which will likely be a pain in the rear. Right now, the user can create the html report and print to pdf from the browser (not sure if this works cross platform but it does on linux).

**Comment by rkingdc** [comment]
above my pay grade. Closing, never gonna happen.
