### ISSUE TITLE
I'd like to change the license from GPL to something that isn't copyleft

### ISSUE THREAD

**Issue by moorepants** [ucd-ipo/aip-analysis#2]
BSD, MIT, or Apache are preferable.

Unless there is a specific reason for needing GPL features, i.e. forcing downstream users to use the same license, then we should remove that restriction and choose a more liberal license that only requires essentially "citation".

**Comment by msimmond** [comment]
This is what I was asking about at the last meeting. Jason, do you think there's anyway to link the presentation materials I'm creating in powerpoint to the app in github? I'd like people to be able to use the ppt materials, but with a citation.

**Comment by moorepants** [comment]
If you have some presentation materials that you'd like people to find via the app (i.e. a link inside the app) then I would host the materials online somewhere (probably not in this particular Github repo) like slideshare, figshare or on a website that your group has control over and we can add the link to the app. I would recommend using the Creative Commons Attribution 4.0 license for the slides. Also, I'd recommend saving as PDF or even .opd (libre/open office format) so that anyone can view it without having to buy software.

**Comment by moorepants** [comment]
@lmpincus I'd like to change the license from the [GNU Public License](http://opensource.org/licenses/gpl-license) to the [Berkeley Source Distribution](http://opensource.org/licenses/BSD-3-Clause) license. The fundamental difference is that the GPL requires anyone that reuses this code to also make their code open source with the GPL where as the BSD license simply requires the user to include the previous license with any changes, basically a citation that travels with the code (very similar to the Creative Commons By license).

Do you have any objections to that?

**Comment by lmpincus** [comment]
No objections to changing the license to the Berkeley Source Distribution.

**Comment by moorepants** [comment]
Thanks. I'll update soon.
