### ISSUE TITLE
Let users set units on plots

### ISSUE THREAD

**Issue by moorepants** [ucd-ipo/aip-analysis#37]
See: https://github.com/ucd-ipo/aip-analysis/pull/34#discussion_r35814628

**Comment by moorepants** [comment]
A simple solution for this is that the user just includes the units in the column name of their uploaded data. Then the units will all show up in the graphs (except when transformations are applied.).

**Comment by rkingdc** [comment]
This isn't designed for publication quality plots. If the user wants units, Microsoft Paint is a handy tool.
