### ISSUE TITLE
Dealing with datasets that have missing values

### ISSUE THREAD

**Issue by msimmond** [ucd-ipo/aip-analysis#38]
We'll have to figure out how to do this, but for now as a reminder...
Excerpt from "http://www.unh.edu/halelab/BIOL933/lectures/lect_16_reading.pdf":
'In summary, a major problem in the analysis of unbalanced data is the contamination of means,
and thus the differences among means, by effects of other factors. The solution to these
problems is to replace missing data by their least square estimates and to remove the
contaminating effects of other factors through a proper adjustment of means. With R, all this
means is that you should use the Type II SS (Anova()) and the lsmeans() function.'

**Comment by moorepants** [comment]
Maybe the app should require that you don't have missing values for now.

**Comment by moorepants** [comment]
Suggested reading from Maegen:

On missing data:
http://www.unh.edu/halelab/BIOL933/lectures/lect_16_reading.pdf
http://www.unh.edu/halelab/BIOL933/labs/lab8.pdf

**Comment by rkingdc** [comment]
The imputation scheme suggested is problematic, and I don't think it's worth the effort it would take to do it right. Maybe someday. Not today.
