### ISSUE TITLE
examples of testing assumptions (normality by shapiro-wilk, HOV by Levene's) for split-plot designs

### ISSUE THREAD

**Issue by msimmond** [ucd-ipo/aip-analysis#39]
@lmpincus Help! I can't find this!

**Comment by moorepants** [comment]
@msimmond Is this now resolved? These are still the same in the split plot example.

**Comment by moorepants** [comment]
The app uses the model without the Error() term to run all of these tests. If that is incorrect this can be reopened.

**Comment by msimmond** [comment]
As far as I know it's correct. However, I'm not sure that we shouldn't be testing normality using Shapiro-Wilk. I'm reaching out to some other stats people to see what's done for split-plots and mixed effects.
