### ISSUE TITLE
plots for checking assumptions

### ISSUE THREAD

**Issue by msimmond** [ucd-ipo/aip-analysis#46]
Two things:
- Can you please update the parameters for the plot(model...) so that there is less white space between subplots? I found this to work:
  par(mfrow = c(2, 1), oma = c(0, 0, 2, 0),
  mar = c(4,4,2,2))

-Can you please change the 2 plots produced to: (1) res x pred (already there) and (2) histogram or kernel density plot (I think we were calling it) - instead of QQ

**Comment by moorepants** [comment]
Done, see: https://moorepants.shinyapps.io/aftsp

**Comment by moorepants** [comment]
Here is a nice post showing why a Q-Q plot is better than a histogram comparison (also why Shapiro-Wilk isn't useful): http://allendowney.blogspot.com/2013/08/are-my-data-normal.html

**Comment by msimmond** [comment]
@ikkyle After meeting with group, we decided that we want the plots produced with the assumption tests to include: (1) Residuals x Predicted, (2) Q-Q plot, (3) kernel density plot, and (4) box plot. I think most of the scenarios have 1, 2, and 4, but 3 is missing from all or most of them.

**Comment by rkingdc** [comment]
private email discussing this deciding to not do QQ. 1, 3, 4 are included
