### ISSUE TITLE
shinyBS >.5 and readxl now on cran

### ISSUE THREAD

**Issue by rkingdc** [ucd-ipo/aip-analysis#5]
The packages shinyBS and readxl are on CRAN now, so the install_github part of the initialize_AIP() function for those packages can be changed to install.packages and the section of code loading readxl and using read_excel can be uncommented. Users should now be able to upload excel files!

**Comment by rkingdc** [comment]
Oh, and you'll have to add the argument when calling read_excel: "sheet=1" so that it loads the first sheet. Or make a radio button when the user can select what sheet they want. readxl includes a function read_sheets (or something like that) that lists all the sheets in the workbook so you could send those to the radio buttons and have the user select which sheet to read in.

**Comment by moorepants** [comment]
shinyBS is now being pulled from CRAN. The excel functionality hasn't been requested, so I'm leaving that as is for now. Closing this, a new issue can be opened for excel loading functionality.
