### ISSUE TITLE
We need a decent library name

### ISSUE THREAD

**Issue by moorepants** [ucd-ipo/aip-analysis#50]
So Lauren said we should call this the "Agricultural Field Trial Statistics Package". That is a mouthful so we need something simpler for the library name. We could make an acronym: "AFTSP" or "AFTS" but I'm not really fond of that. Ian named it "AIP", which I don't even know what it stands for.

What do you all think about "Chaval"? It is the Urdu word for "rice".

So "Chaval: An Agricultural Field Trial Statistics Package" and you would install and load it with:

``` r
install.packages('chaval')
library('chaval')
chaval()
```

**Comment by moorepants** [comment]
@msimmond @lmpincus

**Comment by msimmond** [comment]
if you install this package, will it open the app for any R user?

**Comment by msimmond** [comment]
AIP stands for Agricultural Innovation Project, but it's an umbrella project and this is just one subproject.

**Comment by msimmond** [comment]
Some ideas:
- Friendly Statistics for Agricultural Scientists (FSAS)
- Quick Stats for Agricultural Scientists (QSAS) 
- Quick Statistics for Agricultural Scientists (QSAS) 
- Statistics for Agricultural Scientists (SAS) ha!
- Chaval: A Statistics Package for Agricultural Scientists

**Comment by moorepants** [comment]
I'm not a fan of acronyms, that's why I tried to find an Urdu agricultural word that might work (since it will first be used in Pakistan). If you want this package to be on CRAN, then you'll have to make sure that the actual package name (the short version) isn't already taken.

> if you install this package, will it open the app for any R user?

If we get the package accepted to CRAN, then anyone can install R and simply type `install.package('our.package.name')` and they can run the app.

The R package name should be short, but we can have dual names, one short for using in R and the other longer multi-word one for displaying and such.

Other popular R package names might have "R" or "r" in it. Like `knitr`, `Rmisc`, etc. Maybe something can be made with "agriculture" or "ag" or "aggie". What about: "cropr" or "cRop" or "rcrop"?

You all can decide on the name as you all have to live with it longer than me. But it'd be nice to choose something and get all the branding unified.

**Comment by moorepants** [comment]
I talked with some people that speak Urdu. Here are a couple candidates:
- beej : seed
- kheyt : farm

**Comment by rkingdc** [comment]
Made an executive decision:
Calling it "agroft"
Agriculture, R, open source, field trial. Easy to say, and spells like it's pronounced. 
Didn't have time to dwell to much on this decision, have to have everything done by wednesday night.
