### ISSUE TITLE
Change the formula debug message into a proper display of the formula.

### ISSUE THREAD

**Issue by msimmond** [ucd-ipo/aip-analysis#52]
"error: subscript out of bounds"

It still seems to work, but the error pops up.

**Comment by moorepants** [comment]
That's likely just a debug message that I have displayed temporarily. Not sure though. Can you post a screen shot or specify exactly how to reproduce it and where is shows up?

**Comment by msimmond** [comment]
![screen shot 2015-08-18 at 12 12 29 pm](https://cloud.githubusercontent.com/assets/7077355/9340041/7498e390-45a2-11e5-995e-69b4136ab1b0.png)

**Comment by msimmond** [comment]
..after loading the csv
![screen shot 2015-08-18 at 12 14 33 pm](https://cloud.githubusercontent.com/assets/7077355/9340097/bc527d86-45a2-11e5-9124-f554a16e6551.png)

**Comment by moorepants** [comment]
Thanks, that top bar that eventually displays the formula is just for debugging at the moment. I'll change it to display the formula properly for the final app.

**Comment by msimmond** [comment]
Cool thanks.

On Tue, Aug 18, 2015 at 12:41 PM, Jason K. Moore notifications@github.com
wrote:

> Thanks, that top bar that eventually displays the formula is just for
> debugging at the moment. I'll change it to display the formula properly for
> the final app.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ucd-ipo/aip-analysis/issues/52#issuecomment-132329106
> .

## 

Maegen Simmonds, Ph.D.
mbsimmonds@ucdavis.edu
707-694-6079
