### ISSUE TITLE
Remove the square root option for transformation

### ISSUE THREAD

**Issue by msimmond** [ucd-ipo/aip-analysis#55]
It's redundant since the power transformation can do this. Also sq root is more common for count data which we aren't allowing for the dependent variable.

**Comment by moorepants** [comment]
> It's redundant since the power transformation can do this.

Sorta. You'll only get the explicit sqrt if the power calculation happens to compute 0.5 as the answer. I'll remove it though.

**Comment by rkingdc** [comment]
we decided to keep it. Private email with Maegen and I.
