### ISSUE TITLE
Add subtitle to model fit summary and move the ANOVA table

### ISSUE THREAD

**Issue by msimmond** [ucd-ipo/aip-analysis#58]
- [x] In Analysis tab, under 'Model Fit Summary', add subtitle, 'ANOVA table'.
- [ ] Also move this output to below assumption tests.

**Comment by moorepants** [comment]
Do you want the "Model Fit Summary", "Residuals vs Fitted", "Kernel Density of the Residuals", and "Box Plots" all below the two/three assumptions tests? Right now it is in an order that matches the order of the code. Or do you want everything the same except moving the `summary(fit)` call to the end of the script?
