### ISSUE TITLE
Include resources in the application

### ISSUE THREAD

**Issue by moorepants** [ucd-ipo/aip-analysis#6]
From @msimmond:

> This is what I was asking about at the last meeting. Jason, do you think there's anyway to link the presentation materials I'm creating in powerpoint to the app in github? I'd like people to be able to use the ppt materials, but with a citation.

Sounds like we need some way to host general materials like a Powerpoint and have them accessible to from the application.

**Comment by moorepants** [comment]
@msimmond Can you describe what you mean more? Is this powerpoint something you want the people to be able to view from the application? And do they need to be able to view it if they do not have access to the internet?

**Comment by msimmond** [comment]
Maybe it can be something that's available online and also through the app in case they don't have internet access.

**Comment by moorepants** [comment]
Ok, if you want to make a PDF of the materials that may be the easiest to provide through a download from the app.

**Comment by msimmond** [comment]
I will do that, but I'm also interested in doing a slide viewer option since the animations can be helpful. Apparently Microsoft has a free powerpoint viewer: https://support.office.com/en-gb/article/View-a-presentation-without-PowerPoint-2010-2f1077ab-9a4e-41ba-9f75-d55bd9b231a6

**Comment by moorepants** [comment]
We could possibly ship that program with the app but it only runs on Windows according to this:

https://www.microsoft.com/en-us/download/details.aspx?id=13

What exactly are the materials that you want included in the app? Maybe it can just be on the help pages or something?

If you can give me more details on what you want exactly you are trying to do I can suggest ways that it can be included as a native part of the application.

**Comment by rkingdc** [comment]
You could write the slideshow in markdown, compile it in html and it could run in the app or it would open in any web browser so it would be cross platform

http://rmarkdown.rstudio.com/slidy_presentation_format.html

**Comment by msimmond** [comment]
That would be awesome, but I already created the presentations in powerpoint. What Jason suggested about converting them to PDF and having them downloadable through the app sounds like the easiest way.

**Comment by rkingdc** [comment]
they are on the about page.
