### ISSUE TITLE
Variance-weighted ANOVA example

### ISSUE THREAD

**Issue by msimmond** [ucd-ipo/aip-analysis#65]
Following up on #13 here's an example of a variance-weighted ANOVA that can be performed if transformations don't resolve the problems with assumption tests for the scenario 'CRD with 1 treatment':

Instead of assuming equal variance with: model <- aov(y ~ group, data = my.data)
Do variance-weighted ANOVA that does not assume equal variances. There could be option below transformation drop-down to do that, but don't allow transformation + variance-weight ANOVA.
oneway.test(y ~ group, data = my.data)
(Source: https://stat.ethz.ch/R-manual/R-devel/library/stats/html/oneway.test.html)

**Comment by rkingdc** [comment]
nope.
