### ISSUE TITLE
Impossible to install devtools on Ubuntu 14.04 LTS with apt r-base version

### ISSUE THREAD

**Issue by moorepants** [ucd-ipo/aip-analysis#74]
See: https://github.com/hadley/devtools/issues/847

I somehow have devtools installed on my laptop (14.04) but when I tried on another machine (also 14.04) devtools fails to install rversions because of a missing xml2 dependency.

One solution is to install a newer version of R from another repository, but that is such a headache for users to do. In my opinion, devtools should work with 14.04 (it is the current LTS release!).

**Comment by moorepants** [comment]
This means that devtools probably shouldn't be a dependency. We need to ship shinyAce 0.2.0 with the app somehow so users can install from a tarball.

**Comment by rkingdc** [comment]
This provides another dependency problem. Windows users will need Rtools
installed to build from source. That is a separate executable file to
download from CRAN and another step beyond installing base R.

**Comment by rkingdc** [comment]
Oh wait, we can distribute a binary (hopefully). Disregard.

**Comment by moorepants** [comment]
I noticed that devtools requires different steps on Windows too.

Is there any reason I can't use the version of shinyAce that is on CRAN?

**Comment by rkingdc** [comment]
I think it was either 0.5 or 0.6 that the app depends on. Check the
DESCRIPTION file. I think CRAN version is at 0.6.1 or something. So it
should be fine.

**Comment by moorepants** [comment]
I think you are talking about shinyBS. shinyAce is the hold up. It has version 0.1.0 on CRAN but 0.2.0 on github.

**Comment by rkingdc** [comment]
ah whoops. Yeah I was confused. Sorry. I know it won't work with the
earlier version because of a missing function in the old version, and I
think it is one of the functions that makes the code that is displayed
dynamic.

**Comment by moorepants** [comment]
I switched to shinyAce 0.1.0 and only had to remove the wordwrap argument. Seems to work fine.

**Comment by rkingdc** [comment]
ohhhh right. that was it. Just make sure long formulas and stuff don't run
off the page.

**Comment by moorepants** [comment]
Closing this, it's just a problem endemic to R packaging, it is not the culture to support "old" versions of R, nor is `install.packages()` useful for installing anything but the latest versions of packages. Typically, in app development you want to pin you app to specific versions of the dependencies, otherwise it is bound to break when downstream packages have backwards incompatibilities.
