### ISSUE TITLE
Confirm whether Error() term is correct for split-plot designs with RCBD main plots

### ISSUE THREAD

**Issue by msimmond** [ucd-ipo/aip-analysis#75]
Currently in app it's: Error(MainPlot:Block)

Example where it's Error(MainPlot:Block):
(see p 2) http://www.unh.edu/halelab/BIOL933/labs/lab9.pdf

Example where it's Error(Block/MainPlot):
(see p 13) https://stat.ethz.ch/education/semesters/as2011/anova/Slid10.pdf

**Comment by rkingdc** [comment]
Using mixed effects now. Closing.
