### ISSUE TITLE
make sure type III SS are provided in all ANOVA tables (Not type I SS)

### ISSUE THREAD

**Issue by msimmond** [ucd-ipo/aip-analysis#77]
From: http://www.statmethods.net/stats/anova.html
3. Evaluate Model Effects
WARNING: R provides Type I sequential SS, not the default Type III marginal SS reported by SAS and SPSS. In a nonorthogonal design with more than one term on the right hand side of the equation order will matter (i.e., A+B and B+A will produce different results)! We will need use the drop1( ) function to produce the familiar Type III results. It will compare each term with the full model. Alternatively, we can use anova(fit.model1, fit.model2) to compare nested models directly.
summary(fit) # display Type I ANOVA table
drop1(fit,~.,test="F") # type III SS and F Tests

**Comment by rkingdc** [comment]
I'm going to switch to using the `Anova()` function from the `car` package. It's more straightforward than `drop1`
