### ISSUE TITLE
comments on current app

### ISSUE THREAD

**Issue by msimmond** [ucd-ipo/aip-analysis#78]
For CRD1, CRD2, RCBD1, RCBD2:

-I noticed that in a CRD1, with a sig trt effect, the bar plot doesn't show all the treatment levels. I think it's set to only show the treatment levels that are significantly different. However, it should show all of them.

-Can't download report
-Edit my name in authors to:  (note the 'en' in Maegen)
-Remove Tukey test for CRD2
-Reset everything after reloading new data. Without refreshing page first, the post-hoc tests can fail and you also can't see if a transformation is selected in the drop-down.
-Add function to customize axis in graphs - currently no units are shown
-post-hoc output not customized for transformed variable

I know some of these you already mentioned in your email, but just noting again.

**Comment by moorepants** [comment]
> I noticed that in a CRD1, with a sig trt effect, the bar plot doesn't show all the treatment levels. I think it's set to only show the treatment levels that are significantly different. However, it should show all of them.

When I run the sweetpotato data with CRD1 I see all four of the treatment levels in the bar plot on the post hoc tab. You'll need to provide me with enough information to reproduce what you see.

> Can't download report

This works fine for me on the app website., you'll have to explain more about what does and doesn't happen.

> Edit my name in authors to: Maegen B. Simmonds (note the 'en' in Maegen)

Done.

> Remove Tukey test for CRD2

Done.

> Reset everything after reloading new data. Without refreshing page first, the post-hoc tests can fail and you also can't see if a transformation is selected in the drop-down.

Already reported at issue #49

> Add function to customize axis in graphs - currently no units are shown

Reported at #37

**Comment by moorepants** [comment]
Closing, the first issue is moved to #79.
