### ISSUE TITLE
Determine what operating systems we need to support.

### ISSUE THREAD

**Issue by moorepants** [ucd-ipo/aip-analysis#8]
Do we need to support other operating systems other than Windows?

**Comment by lmpincus** [comment]
How much trouble is it to also include Mac? I would suspect that the majority of users are Windows.

**Comment by moorepants** [comment]
Mac and Linux will likely run fine with no extra work. It's just that ensuring we can run it on older computers that may have old Windows in developing countries is harder.

Do you have a feel for what kinds of computers this will need to run on?

**Comment by lmpincus** [comment]
Yeah, I would say definitely we can expect some users to have older versions of Windows running on older computers.

**Comment by moorepants** [comment]
@msimmond @lmpincus Has any information on this been obtained? I think the last thing was that one of you would ask Mark what operating systems to support. I need to know operating system, operating system versions, and whether 32/64 bit.

**Comment by moorepants** [comment]
@msimmond I still need to know this info. Thanks.

**Comment by moorepants** [comment]
Mark:

> Is there anyway of saying what the most common operating systems are in Pakistan? OS and whether 32 or 64 Bit is more common?

Farjeel:

> The answer to you question is that Windows OS is the most common platform in Pakistan and mostly its 32 bit. 

All Windows versions have 32 bit options. We still need to know what version of Windows, especially if Windows XP is expected to work. There may be issues getting a modern browser working on Windows XP.

**Comment by rkingdc** [comment]
cross platform. Works everywhere.
