### ISSUE TITLE
May need to change split plot from aov to mixed effects

### ISSUE THREAD

**Issue by moorepants** [ucd-ipo/aip-analysis#82]
See this discussion: https://groups.google.com/forum/#!topic/davis-rug/PnbK2ZDi9tM

**Comment by msimmond** [comment]
Yes, after consulting several sources we need to change the statistical approach for split-plot designs from fixed effect model using aov() to mixed effects model using lmer() or lme(). I'll check to see if the split-plot design code is still in the pull requests so I can edit it there.

**Comment by msimmond** [comment]
@ikkyle I'm not sure how to go about editing the two split-plot scenarios (CRD type and RCBD type). Can you add them to the pull requests? Or is there a new place to edit since a lot of those drafts were merged to the master code?

**Comment by moorepants** [comment]
If you go here: https://github.com/ucd-ipo/aip-analysis/blob/master/examples/split_plot_rcbd.R and then click the pencil you can edit the example. It will then give you an option to create a pull request or directly commit the changes to the master code. You can do that with any file in the repository.

**Comment by moorepants** [comment]
There is also this desktop program https://desktop.github.com/ that would let you edit the files on your Mac.

**Comment by msimmond** [comment]
Thanks, @moorepants.

**Comment by rkingdc** [comment]
This should be working now for split plot RCBD using `nlme`. I was a bit confused and didn't include split plot completely randomized design, but I'll work that in soon.

**Comment by msimmond** [comment]
Can you please merge the pull request that I made for the split plot RCBD, but with your changes to the nlme model? I'd like to have all the examples in their final form if possible.

**Comment by rkingdc** [comment]
Done. What should the split plot CRD formula look like?

**Comment by msimmond** [comment]
model <- lme(fixed = Y ~ A*B,
             random = ~1|Rep/A,
              data = my.data), where A is main-plot, B is sub-plot, and Rep is experimental unit for main-plot.

**Comment by rkingdc** [comment]
Done.
