### ISSUE TITLE
Add Randomized Complete Block Design Options

### ISSUE THREAD

**Issue by moorepants** [ucd-ipo/aip-analysis#9]
- [x] Must be able to analyze CRD (completely randomized design) and RCBD, there should be option for 1 and 2 treatments, and their interaction:
  - Y ~ trtA
  - Y ~ trtA trtB trtA*trtB
  - Y ~ trtA Block
  - Y ~ trtA trtB trtA*trtB Block 
- [ ] Add a reminder that pops up anytime there’s a significant treatment x treatment interaction, that main effects can not be evaluated.

**Comment by moorepants** [comment]
This is complete, there is no reminder because it automatically determines whether main effects can be evaluated.

**Comment by msimmond** [comment]
Is it easy to have the reminder anyway? that way the user will know what to expect in the post-hoc analyses.

**Comment by moorepants** [comment]
Sure, try out the app now that the post hoc stuff works and tell me where you'd want to see a reminder and what exactly it should say. Right now it already says things like "interaction is significant" "interaction is not significant", etc.

**Comment by msimmond** [comment]
I'm going to hold off on changing those reminders right now. But I do have
a few comments on the current app...

In Analysis tab,
- Under 'Model Fit Summary', add subtitle, 'ANOVA table'. Also move this
  output to below assumption tests.
- Edit title 'Tukey's Test' to 'Tukey's Test for Nonadditivity'
- Change the squared predicted variable name to something consistent for
    any scenario, such as 'sq.pred'.
  - Can you remove all rows in the Tukey's ANOVA table except for
    'sq.pred'? If not, add subtitle to 'Tukey's Test for Nonadditivity':
    'Attention: refer only to 'sq.pred' in this table - ignore all other rows'

In Post-hoc tests tab,
- Change the title to 'Post-hoc tests and figures'
- Still need to update for transformed data scenarios: #1 add LSD table
  for original data with the grouping letters replaced with the transformed
  data LSD table below the LSD output for transformed data. #2 replace the
  bar plot with #1

On Wed, Aug 19, 2015 at 10:09 AM, Jason K. Moore notifications@github.com
wrote:

> Sure, try out the app now that the post hoc stuff works and tell me where
> you'd want to see a reminder and what exactly it should say. Right now it
> already says things like "interaction is significant" "interaction is not
> significant", etc.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ucd-ipo/aip-analysis/issues/9#issuecomment-132697709.

## 

Maegen Simmonds, Ph.D.
mbsimmonds@ucdavis.edu
707-694-6079

**Comment by moorepants** [comment]
All this stuff is fine, would you mind opening issues for each separate item? (and for any new things you want changed). It is easier to keep track of things and organize what needs to be done if we make separate issues.

**Comment by msimmond** [comment]
Sure, thanks for the reminder. Still getting used to GitHub. It's awesome!

On Wed, Aug 19, 2015 at 12:06 PM, Jason K. Moore notifications@github.com
wrote:

> All this stuff is fine, would you mind opening issues for each separate
> item? (and for any new things you want changed). It is easier to keep track
> of things and organize what needs to be done if we make separate issues.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ucd-ipo/aip-analysis/issues/9#issuecomment-132744965.

## 

Maegen Simmonds, Ph.D.
mbsimmonds@ucdavis.edu
707-694-6079
