### ISSUE TITLE
`yield.pred.sq` row missing from Tukey test?

### ISSUE THREAD

**Issue by rkingdc** [ucd-ipo/aip-analysis#90]
Using the following parameters, 

Data: split-plot design
Experimental Design: Split-Plot RCBD
DV: yield
IVs:
  main plot treatment: A
  sub plot treatment: plot
  blocking factor variable: block
Transformations: None

Under Tukey's Test for Nonadditivity, a message says to "refer to only the 'yield.pred.sq' row in this table...", but there is no such row in the table. Only a row for 'A', 'plot', and 'Residuals'. Is this an error?

**Comment by moorepants** [comment]
The row should be there if it runs the Tukey test. It is an error if not.

**Comment by msimmond** [comment]
I deleted the Tukey 1df Test for the split-plot RCBD example (see pull request), as I think we should only use it for the basic RCBD with a single treatment rep per block.

**Comment by rkingdc** [comment]
In the ANOVA table output, we also get the error 

```
Error in MEEM(object, conLin, control$niterEM) : 
Singularity in backsolve at level 0, block 1
```

I'm pretty sure this has to do with the data not being nested but the model is trying to analyze it as if the data are nested. I'll need to implement an error handler that is more informative for this issue.

**Comment by rkingdc** [comment]
@msimmond I just want to confirm that we don't want to run the tukey test for split plot designs?

**Comment by msimmond** [comment]
That's correct.

**Comment by rkingdc** [comment]
@msimmond Tukey 1-df test is for 2-way ANOVA only, correct? So should we only be doing this for RCBD2 and CRD2?

**Comment by msimmond** [comment]
Tukey 1-df test is for the RCBD tests only (i.e. RCBD1 and RCBD2). Not for
any CRD or split-plot.

Maegen Simmonds
Postdoctoral Scholar
Earth Systems Science
Stanford University
Green Blg, Rm 321
Stanford, CA 94305
Phone: (707) 694-6079
mbsimmonds@stanford.edu

**Comment by rkingdc** [comment]
fixed
