### ISSUE TITLE
Empty interaction plots

### ISSUE THREAD

**Issue by rkingdc** [ucd-ipo/aip-analysis#92]
Should we hide interaction plots when there are no interactions in the model? Split-plot RCBD returns empty interaction plots in the case mentioned in issue [#90](https://github.com/ucd-ipo/aip-analysis/issues/90)

**Comment by msimmond** [comment]
If there aren't any interactions in the model, then yes, hide the interaction plots. However, the split-plot RCBD has an interaction term, and I was able to get the interaction plots with the edited code - see pull request for split_plot_rcbd.R.
